name: 'First-Job'
description: 'Created by DSL Seed-Job'
gitUrl : 'https://github.com/gobindadas/GroovyCore.git'
branchName: 'master'
parameters :
 - type: string
   name: NBC_APPNAME
   value: CHANGEME
   description: 'Application name'
 - type: string
   name: NBC_BUILDID
   value: CHANGEME
   description: 'Job build Id'
 - type: string
   name: NBC_ARTIFACT
   value: CHANGEME
   description: 'Application artifact Id'
 - type: boolean
   name: DEV
   value: true
   description: 'This job is for Dev build or not.'
schedule: 'H/5 * * * *'
mavenCMD: 'clean install'
shellCMD: 'sudo apt-get update'
assignedNode: 'Supercatalyst'
recipients: 'gobinda.das@relevancelab.com'