name: 'First-Job'
description: 'Created by DSL Seed-Job'
gitUrl : 'https://github.com/gobindadas/GroovyCore.git'
parameters :
 - type: string
   name: NBC_APPNAME
   value: CHANGEME
 - type: string
   name: NBC_BUILDID
   value: CHANGEME
 - type: string
   name: NBC_ARTIFACT
   value: CHANGEME
mavenCMD: '-e clean test'
shellCMD: 'sudo apt-get update'